[package]
name    = "term_status"
authors = ["David Armstrong Lewis <david@armstronglewis.com>"]
version = "0.3.0"
edition = "2018"

[dependencies]
ansi_term   = "0.11.0"
git2        = "0.9.1"
derive_more = "0.15.0"
dirs = "2.0.1"
